# Generated by Django 4.1.5 on 2023-02-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=150, verbose_name='Raça')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.especie', verbose_name='Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('nome_dono', models.CharField(max_length=200, verbose_name='Nome Completo do Dono')),
                ('email_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-mail 01')),
                ('email_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-mail 02')),
                ('fone_1', models.CharField(max_length=15, verbose_name='Fone 01')),
                ('fone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fone 02')),
                ('fone_3', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fone 03')),
                ('obs', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço')),
                ('numero', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número')),
                ('complemento', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Complemento')),
                ('nome_pet', models.CharField(max_length=200, verbose_name='Nome do Pet')),
                ('idade', models.CharField(choices=[('Desconhecida', 'Desconhecida'), ('01 Mês', '01 Mês'), ('02 Mêses', '02 Mêses'), ('03 Mêses', '03 Mêses'), ('04 Mêses', '04 Mêses'), ('05 Mêses', '05 Mêses'), ('06 Mêses', '06 Mêses'), ('07 Mêses', '07 Mêses'), ('08 Mêses', '08 Mêses'), ('09 Mêses', '09 Mêses'), ('10 Mêses', '10 Mêses'), ('11 Mêses', '11 Mêses'), ('01 Ano', '01 Ano'), ('02 Anos', '02 Anos'), ('03 Anos', '03 Anos'), ('04 Anos', '04 Anos'), ('05 Anos', '05 Anos'), ('06 Anos', '06 Anos'), ('07 Anos', '07 Anos'), ('08 Anos', '08 Anos'), ('09 Anos', '09 Anos'), ('10 Anos', '10 Anos'), ('11 Anos', '11 Anos'), ('12 Anos', '12 Anos'), ('13 Anos', '13 Anos'), ('14 Anos', '14 Anos'), ('15 Anos', '15 Anos'), ('16 Anos', '16 Anos'), ('17 Anos', '17 Anos'), ('18 Anos', '18 Anos'), ('19 Anos', '19 Anos'), ('20 Anos', '20 Anos'), ('21 Anos', '21 Anos'), ('22 Anos', '22 Anos'), ('23 Anos', '23 Anos'), ('24 Anos', '24 Anos'), ('25 Anos', '25 Anos'), ('26 Anos', '26 Anos'), ('27 Anos', '27 Anos'), ('28 Anos', '28 Anos'), ('29 Anos', '29 Anos'), ('30 Anos', '30 Anos')], max_length=15)),
                ('sexo', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('qualidades', models.CharField(max_length=2000, verbose_name='Qualidades')),
                ('img', models.ImageField(upload_to='Adocao_fotos/', verbose_name='Foto')),
                ('status', models.CharField(choices=[('d', 'Disponível'), ('a', 'Adotado'), ('c', 'Adoção Cancelada')], max_length=1)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.especie', verbose_name='Especie')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.raca', verbose_name='Raça')),
            ],
        ),
    ]
