# Generated by Django 4.1.5 on 2023-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_adocao_cadastrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='email_1',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail 01'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='email_2',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail 02'),
        ),
    ]
