# Generated by Django 4.1.5 on 2023-01-29 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Idade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(max_length=10, unique=True, verbose_name='Idade')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10, unique=True, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, unique=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=150, verbose_name='Raça')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.especie', verbose_name='Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dono', models.CharField(max_length=200, verbose_name='Nome Completo do Dono')),
                ('email_1', models.CharField(max_length=150, null=True, verbose_name='E-mail 01')),
                ('email_2', models.CharField(max_length=150, null=True, verbose_name='E-mail 02')),
                ('fone_1', models.CharField(max_length=15, null=True, verbose_name='Fone 01')),
                ('fone_2', models.CharField(max_length=15, null=True, verbose_name='Fone 02')),
                ('fone_3', models.CharField(max_length=15, null=True, verbose_name='Fone 03')),
                ('obs', models.CharField(max_length=2000, null=True, verbose_name='Observações')),
                ('cep', models.CharField(max_length=8, null=True, verbose_name='CEP')),
                ('estado', models.CharField(max_length=2, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=200, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=200, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=250, null=True, verbose_name='Endereço')),
                ('numero', models.IntegerField(default=0, null=True, verbose_name='Número')),
                ('complemento', models.CharField(max_length=2000, null=True, verbose_name='Complemento')),
                ('nome_pet', models.CharField(max_length=200, verbose_name='Nome do Pet')),
                ('qualidades', models.CharField(max_length=2000, verbose_name='Qualidades')),
                ('img', models.ImageField(upload_to='Adocao_fotos/', verbose_name='Foto')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.especie', verbose_name='Especie')),
                ('idade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.idade', verbose_name='Idade')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.raca', verbose_name='Raça')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.sexo', verbose_name='Sexo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.status', verbose_name='Status')),
            ],
        ),
    ]
