# Generated by Django 4.1.5 on 2023-01-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(max_length=10, unique=True, verbose_name='Idade')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10, unique=True, verbose_name='Sexo')),
            ],
        ),
        migrations.AlterField(
            model_name='raca',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.especie', verbose_name='Especie'),
        ),
    ]
