# Generated by Django 4.1.5 on 2023-01-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adocao',
            name='status',
        ),
    ]
