# Generated by Django 4.1.5 on 2023-01-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='sexo',
            field=models.CharField(choices=[('Indefinido', 'Indefinido'), ('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10),
        ),
    ]
