# Generated by Django 4.1.5 on 2023-01-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_remove_adocao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adocao',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pet.status', verbose_name='Status'),
            preserve_default=False,
        ),
    ]
