# Generated by Django 4.1.5 on 2023-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_adocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='adocao',
            name='img',
            field=models.ImageField(default=1, upload_to='Adocao_fotos/', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
